### ISSUE TITLE
java.lang.ClassCastException: org.raml.nodes.snakeyaml.SYNullNode cannot be cast

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#28]
got this error:

``` yaml

Exception in thread "main" java.lang.ClassCastException: org.raml.nodes.snakeyaml.SYNullNode cannot be cast to org.raml.impl.v10.nodes.types.builtin.TypeNode
    at org.raml.impl.commons.nodes.AnnotationTypeNode.getTypeNode(AnnotationTypeNode.java:45)
    at org.raml.impl.commons.phase.AnnotationValidationPhase.apply(AnnotationValidationPhase.java:45)
    at org.raml.impl.v10.Raml10Builder.build(Raml10Builder.java:66)
    at org.raml.RamlBuilder.build(RamlBuilder.java:93)
    at org.raml.RamlBuilder.build(RamlBuilder.java:67)
    at org.raml.RamlValidator.main(RamlValidator.java:37)

```

using the following raml:

``` yaml
#%RAML 1.0
title: Illustrating annotations
mediaType: application/json
annotationTypes:
  experimental:
  feedbackRequested:
  testHarness:
    type: string # This line may be omitted as it's the default type
  badge:         # This annotation type, too, allows string values
  clearanceLevel:
    type: object
    properties:
      level:
        enum: [ low, medium, high ]
        required: true
      signature:
        type: string
        pattern: "\\d{3}-\\w{12}"
        required: true
/groups:
  (experimental):
  (feedbackRequested):
/users:
  (testHarness): usersTest
  (badge): tested.gif
  (clearanceLevel):
    level: high
    signature: 230-ghtwvfrs1itr
  get:
    (experimental):
    (feedbackRequested):
    responses:
      200:
```

**Comment by eleonoraortega** [comment]
The problem was S. Sugar was not yet supported
