### ISSUE TITLE
Error using simple example 

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#29]
When using the following example for a defined string an error is displayed
# %RAML 1.0

title: API with Examples
types:
 nombre:
   type: string
   example: eleocapa

Error:

java -jar target/rajapa-1.0.0-SNAPSHOT.jar -dump /Users/Eleo/Dropbox/raml_10/examples.raml
Exception in thread "main" java.lang.ClassCastException: org.raml.impl.v10.nodes.types.builtin.StringTypeNode cannot be cast to org.raml.impl.v10.nodes.types.builtin.ObjectTypeNode
    at org.raml.impl.commons.phase.ExampleValidationPhase.apply(ExampleValidationPhase.java:46)
    at org.raml.impl.v10.Raml10Builder.build(Raml10Builder.java:67)
    at org.raml.RamlBuilder.build(RamlBuilder.java:93)
    at org.raml.RamlBuilder.build(RamlBuilder.java:67)
    at org.raml.RamlValidator.main(RamlValidator.java:37)

**Comment by fededonna** [comment]
Done

**Comment by eleonoraortega** [comment]
ok
