### ISSUE TITLE
time-only example should not use quotes to work

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#40]
With the following example the parser displays an error

``` yaml
lunchtime:
   type: time-only # no implications about date or offset
   example: 12:30:00
```

ERROR

Exception in thread "main" java.lang.NumberFormatException: For input string: "12:30:00"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.valueOf(Integer.java:766)
    at org.raml.v2.nodes.snakeyaml.SYIntegerNode.getValue(SYIntegerNode.java:45)
    at org.raml.v2.nodes.snakeyaml.SYIntegerNode.toString(SYIntegerNode.java:51)
    at java.lang.String.valueOf(String.java:2994)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at org.raml.v2.grammar.rule.ErrorNodeFactory.createInvalidNode(ErrorNodeFactory.java:42)
    at org.raml.v2.grammar.rule.DateValueRule.apply(DateValueRule.java:71)
    at org.raml.v2.utils.NodeValidator.validateSingleExampleNode(NodeValidator.java:211)
    at org.raml.v2.utils.NodeValidator.validateScalar(NodeValidator.java:128)
    at org.raml.v2.utils.NodeValidator.validateExample(NodeValidator.java:78)
    at org.raml.v2.impl.commons.phase.ExampleValidationPhase.apply(ExampleValidationPhase.java:47)
    at org.raml.v2.impl.v10.Raml10Builder.build(Raml10Builder.java:69)
    at org.raml.v2.RamlBuilder.build(RamlBuilder.java:101)
    at org.raml.v2.RamlBuilder.build(RamlBuilder.java:74)
    at org.raml.v2.RamlValidator.main(RamlValidator.java:37)

**Comment by fededonna** [comment]
``` yaml
example: 12:30:00
```

is not a valid yaml string, it should be quoted.
